const SET_USER_PROFILE = 'SET_USER_PROFILE'
const SET_USER_PROFILE_PICTURE = 'SET_USER_PROFILE_PICTURE'
const USER_LOGOUT = 'USER_LOGOUT'

export { SET_USER_PROFILE, SET_USER_PROFILE_PICTURE, USER_LOGOUT }
